name: AsyncWorldEdit
main: org.primesoft.asyncworldedit.AsyncWorldEditMain
version: 2.0.1
website: https://github.com/SBPrime/AsyncWorldEdit/wiki
dev-url: https://github.com/SBPrime/AsyncWorldEdit/wiki
description: This plugin attaches into WorldEdit and makes it asynchronous.
authors: [SBPrime]
depend: [WorldEdit, AsyncWorldEditInjector]
softdepend: [BlocksHub, PlotMe, BarAPI]
commands:
  awe:
    description: 'Displays the help for Async world edit.'
    usage: /<command>
    aliases: /awe
permissions:
